src/Entity/Adherent.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Entity\EntityTrait\EnablableEntityTrait;
use App\Entity\EntityTrait\GeolocEntityTrait;
use App\Entity\EntityTrait\HasAccountsTrait;
use App\Entity\EntityTrait\HasEcompteEntity;
use App\Flux\AccountableInterface;
use App\Flux\AccountableObject;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * ApiResource(
 *     attributes={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_VIEW')"},
 *     collectionOperations={
 *         "get"={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_LIST')"},
 *         "post"={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_EDIT')"}
 *     },
 *     itemOperations={
 *         "get"={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_LIST')"},
 *         "put"={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_EDIT') or object.user == user"},
 *     },
 *     normalizationContext={"groups"={"read"}},
 *     denormalizationContext={"groups"={"write"}}
 * ).
 *
 * @ORM\Entity(repositoryClass="App\Repository\AdherentRepository")
 * @ORM\Table(name="adherent")
 * @ORM\HasLifecycleCallbacks()
 */
class Adherent extends AccountableObject implements AccountableInterface
{
    use EnablableEntityTrait;
    use TimestampableEntity;
    use GeolocEntityTrait;
    use HasEcompteEntity;
    use HasAccountsTrait;

    /**
     * @var \Ramsey\Uuid\UuidInterface
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="idmlc", type="string", length=100, nullable=true)
     * @Groups({"read", "write"})
     */
    protected $idmlc;

    /**
     * @var User
     *
     * @ORM\OneToOne(targetEntity="User", cascade={"all"}, mappedBy="adherent", fetch="LAZY")
     */
    protected $user;

    /**
     * @var Groupe
     *
     * @ORM\ManyToOne(targetEntity="Groupe", inversedBy="adherents", fetch="LAZY")
     */
    private $groupe;

    /**
     * @var ArrayCollection|AccountAdherent[]
     * @ORM\OneToMany(targetEntity="AccountAdherent", mappedBy="adherent")
     */
    private $accounts;

    public function __construct()
    {
        $this->accounts = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * Get idmlc.
     *
     * @return
     */
    public function getIdmlc(): ?string
    {
        return $this->idmlc;
    }

    /**
     * Set idmlc.
     *
     * @return $this
     */
    public function setIdmlc(string $idmlc): self
    {
        $this->idmlc = $idmlc;

        return $this;
    }

    public function getCompte(): float
    {
        return $this->getEcompte();
    }

    public function setCompte(float $ecompte): self
    {
        $this->setEcompte($ecompte);

        return $this;
    }

    /**
     * @return User
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User $user
     *
     * @return Prestataire
     */
    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @param Groupe|null $groupe
     *
     * @return $this
     */
    public function setGroupe(?Groupe $groupe): self
    {
        $this->groupe = $groupe;

        return $this;
    }

    /**
     * @return Groupe|null
     */
    public function getGroupe(): ?Groupe
    {
        return $this->groupe;
    }

    public function isEnabled(): bool
    {
        return $this->getUser()->isEnabled();
    }

    public function setEnabled($enabled): self
    {
        $this->getUser()->setEnabled($enabled);

        return $this;
    }

    public function getName(): string
    {
        return $this->__toString();
    }

    public function __toString(): string
    {
        if (!empty($this->getUser())) {
            if (!empty($this->getUser()->getLastname() . $this->getUser()->getFirstname())) {
                return $this->getUser()->getLastname() . ' ' . $this->getUser()->getFirstname();
            }
            if (!empty($this->getUser()->getUsername())) {
                return $this->getUser()->getUsername();
            }
            if (!empty($this->getUser()->getEmail())) {
                return $this->getUser()->getEmail();
            }
        }

        return 'Adhérent xxx';
    }

    public function getEmail(): ?string
    {
        if (!empty($this->getUser())) {
            return $this->getUser()->getEmail();
        }
        return '';
    }

    public function getFullname(): string
    {
        $return = '';
        if (!empty($this->getUser())) {
            if (!empty($this->getUser()->getLastname() . $this->getUser()->getFirstname())) {
                $return = $this->getUser()->getLastname() . ' ' . $this->getUser()->getFirstname();
                if (!empty($this->getUser()->getEmail())) {
                    $return .= '(' . $this->getUser()->getEmail() . ')';
                }
            } elseif (!empty($this->getUser()->getEmail())) {
                $return = $this->getUser()->getEmail();
            }

            return $return;
        }

        return 'Adhérent xxx';
    }
}

templates/themes/kohinos/contact.html.twig
{% extends '@kohinos/common/layout.html.twig' %}

{% form_theme form _self %}

{% block captcha_widget %}
	{% if is_human %}
	-
	{% else %}
		{% apply spaceless %}
			<div class='w-100 text-center mb-2'>
			    <img class="captcha_image d-inline-block" id="{{ image_id }}" src="{{ captcha_code }}" alt="" title="captcha" width="{{ captcha_width }}" height="{{ captcha_height }}" />
			</div>
		    {% if reload %}
		    <script type="text/javascript">
		        function reload_{{ image_id }}() {
		            var img = document.getElementById('{{ image_id }}');
		            img.src = '{{ captcha_code }}?n=' + (new Date()).getTime();
		        }
		    </script>
		    <a class="captcha_reload" href="javascript:reload_{{ image_id }}();">{{ 'Renew'|trans({}, 'gregwar_captcha') }}</a>
		    {% endif %}

		    {{ form_widget(form) }}
		{% endapply %}
	{% endif %}
{% endblock %}


{% block content %}
	<div class='container homepage'>
		{% include '@kohinos/block/breadcrumb.html.twig' with {'label' : 'Contact'} %}
		<div class="card mx-auto mt-2" style="max-width:800px;">
			<div class="card-header">{{ 'Nous contacter'|trans }}</div>
			<div class="card-body">
				<div class="mx-auto text-center" style="max-width:400px;">
					{{form_start(form)}}
						{{ form_row(form.nom) }}
						{{ form_row(form.email) }}
						{{ form_row(form.message) }}
						{{ form_row(form.captcha) }}
						{{ form_row(form.save) }}
					{{form_end(form)}}
		 		</div>
		 	</div>
		</div>
	</div>
{% endblock %}

templates/themes/kohinos/cotiser.html.twig
{% extends '@kohinos/common/layout.html.twig' %}

{% block content %}
<div class='container' style='max-width: 800px;'>
	{% include '@kohinos/block/breadcrumb.html.twig' with {'label': 'Cotiser'} %}
	<h2 class='text-center w-100 mt-4 mb-4'>{{ "Cotiser pour l'année"|trans }} {{ koh_year }}</h2>
	<div class='text-center mb-5'>
		{% if app.user and is_granted('ROLE_ADHERENT') %}
			<h4>{{ 'Solde de eMLC'|trans }} : <b>{{ app.user.adherent.emlcAccount.balance }}</b></h4>
			<h5>{{ 'Montant minimum de la cotisation'|trans }} : <b>{{ KOH_COTISATION_ADHERENT|default('') }} €</b></h5>
			{% if KOH_ADHESION_TEXT|default('') != '' %}
				<br/><p>
					{{ KOH_ADHESION_TEXT }}
				</p>
			{% endif %}
		{% elseif app.user and is_granted('ROLE_PRESTATAIRE') %}
			<h4>{{ 'Solde de eMLC'|trans }} : <b>{{ getCurrentPrestataire().emlcAccount.balance }}</b></h4>
			<h5>{{ 'Montant minimum de la cotisation'|trans }} : <b>{{ KOH_COTISATION_PRESTATAIRE|default('') }} €</b></h5>
		{% endif %}
		<br/>
		{{ form_start(form) }}
			{{ form_row(form.operateur) }}
			{{ form_row(form.role) }}
			{{ form_row(form.reference) }}
			{{ form_row(form.montant) }}
			{% if form.don is defined %}
				{{ form_row(form.don) }}
			{% endif %}
			<div class='row mt-4'>
				{% if form.payMLC is defined %}
					{% if form.payCB is defined %}
						{% if form.payHelloAsso is defined %}
							<div class='col-4'>
								{{ form_widget(form.payMLC) }}
							</div>
							<div class='col-4'>
								{{ form_widget(form.payCB) }}
							</div>
							<div class='col-4'>
								{{ form_widget(form.payHelloAsso) }}
							</div>
						{% else %}
							<div class='col-6'>
								{{ form_widget(form.payMLC) }}
							</div>
							<div class='col-6'>
								{{ form_widget(form.payCB) }}
							</div>
						{% endif %}
					{% endif %}
				{% else %}
					{% if form.payCB is defined %}
						{% if form.payHelloAsso is defined %}
							<div class='col-6'>
								{{ form_widget(form.payCB) }}
							</div>
							<div class='col-6'>
								{{ form_widget(form.payHelloAsso) }}
							</div>
						{% else %}
							<div class='col-12'>
								{{ form_widget(form.payCB) }}
							</div>
						{% endif %}
					{% endif %}
				{% endif %}
			</div>
		{{ form_end(form) }}
	</div>
</div>
{% endblock %}

templates/themes/kohinos/index.html.twig
{% extends '@kohinos/common/layout.html.twig' %}

{% block meta %}
	{{ parent() }}
    {% if KOH_MLC_URL|default('') != '' %}
        <link rel="canonical" href="{{ KOH_MLC_URL }}"/>
        <link rel="preconnect" href="{{ KOH_MLC_URL }}"/>
    {% endif %}
{% endblock meta %}

{% block content %}
    <div class='container homepage'>
    	{# LOGIN MODALE#}
    	{% set modal_id = 'mlcloginmodal' %}
		{% set modal_title = 'Se connecter'|trans %}
		{% set modal_content %}
			{% include '@kohinos/common/login.html.twig' %}
		{% endset %}
		{% include '@kohinos/block/modal.html.twig' with {'btn_primary' : null, 'btn_secondary' : null} %}

		<div class='row mt-3'>
		 	<div class='d-none d-md-block col-12 order-3 order-md-1 col-md-3 order-sm-3 col-sm-12 col-lg-3'>
		 		{% block colonne_gauche %}
					{% include '@kohinos/common/stats.html.twig' %}
					{% include '@kohinos/common/groupes.html.twig' %}
					{% include '@kohinos/common/rubriques.html.twig' %}
				{% endblock colonne_gauche %}
			</div>
			<div class='col-12 order-1 order-md-2 col-md-9 order-sm-1 col-sm-12 col-lg-6 text-center'>
				{% block colonne_centre %}
					<div class='d-block d-sm-block d-md-block d-lg-none'>
						{% include '@kohinos/common/loginbutton.html.twig' %}
					</div>
					{% include '@kohinos/block/useradmin.html.twig' %}
				{% endblock colonne_centre %}
			</div>
			<div class='d-none d-md-block  col-12 order-2 order-md-3 col-md-9 order-sm-2 col-sm-12 col-lg-3'>
				{% block colonne_droite %}
					<div class='d-none d-sm-none d-md-none d-lg-block'>
						{% include '@kohinos/common/loginbutton.html.twig' %}
					</div>
					{% include '@kohinos/common/news.html.twig' %}
				{% endblock colonne_droite %}
			</div>
		</div>
	</div>
	
	{# LOGIN ADHESION HELLOASSO #}
	{% set modal_id = 'mlcadhesionmodal' %}
	{% set modal_title = 'Payer votre cotisation sur Helloasso'|trans %}
	{% set modal_content %}
		<p>Bravo, vous venez de créer votre compte {{ KOH_MLC_NAME|default('') }}.</p>
		<p>Pour pouvoir utiliser celui-ci, vous devez cotiser via HelloAsso sur ce lien :</p><br/>
		<p><a href='{{KOH_HELLOASSO_URL_COTISATION_ADHERENT}}' target='_blank'>COTISER VIA HELLOASSO</a></p>
	{% endset %}
	{% include '@kohinos/block/modal.html.twig' with {'btn_primary' : null, 'btn_secondary' : null} %}

{% endblock %}

{% block js %}
{% include '@kohinos/presta/block/cartejs.html.twig' %}
{% endblock %}

templates/themes/kohinos/index_cotisation_invalid.html.twig
{% extends '@kohinos/common/layout.html.twig' %}

{% block content %}
    <div class='container homepage' style='max-width: 800px;'>
		<div class='row mt-3'>
			<div class='col-12 text-center'>
				{% block colonne_centre %}
					<div class="card border-danger mb-3" style="max-width: 20rem;margin:0 auto;">
					  <div class="card-body">
					    <strong>Votre cotisation n'est pas à jour !</strong>
					    <p>Vous ne pouvez plus utiliser votre compte !</p>
					  </div>
					</div>
					</div>
				{% endblock colonne_centre %}
			</div>
		</div>
	</div>
{% endblock %}

templates/themes/kohinos/index_wordpress.html.twig
{% extends '@kohinos/common/layout.html.twig' %}

{% block content %}
    <div class='container homepage' style='max-width: 800px;'>
		<div class='row mt-3'>
			<div class='col-12 text-center'>
				{% block colonne_centre %}
					{% if app.user is null %}
						{% set modal_id = 'mlcloginmodal' %}
						{% set modal_title = 'Se connecter'|trans %}
						{% set modal_content %}
							{% include '@kohinos/common/login.html.twig' %}
						{% endset %}
						{% include '@kohinos/block/modal.html.twig' %}
						<a class='btn btn-primary w-100 mb-4' data-bs-toggle="modal" data-bs-target="#{{ modal_id }}" title='{{ 'Se connecter'|trans }}' href="{{path('fos_user_security_login')}}">{{ 'Se connecter'|trans }}</a>
					{% endif %}
					{% include '@kohinos/block/useradmin.html.twig' %}
				{% endblock colonne_centre %}
			</div>
		</div>
	</div>
{% endblock %}

templates/themes/kohinos/installation.html.twig
{% extends '@kohinos/common/layout.html.twig' %}

{% form_theme form _self %}

{% block menu %}
{% endblock menu %}

{% block content %}
	<div class='container homepage'>
		<div class="card mx-auto mt-5" style="max-width: 600px;">
			<div class="card-header">{{ 'CONFIGURATION DU KOHINOS'|trans }}</div>
			<div class="card-body">
				<div class="card-text">
					<em>Toutes les informations demandées ci-dessous sont obligatoires mais sont modifiables ensuite dans l'interface d'administration...</em><br/><br/>
					{{ form_start(form)}}
						{{ form_row(form.config) }}
						{{ form_row(form.iban) }}
						{{ form_row(form.website) }}
						<hr class='my-4 bg-primary'/>
						{{ form_row(form.groupe) }}
						<hr class='my-4 bg-primary'/>
						{{ form_row(form.comptoir) }}
						<hr class='my-4 bg-primary'/>
						{{ form_row(form.siege) }}
						<hr class='my-4 bg-primary'/>
						{{ form_row(form.user) }}
						<p><em>
							{{ "A la suite de l'installation du système, un prestataire (un peu particulier : non public, non affiché sur la carte) est crée, avec comme nom 'Monnaie locale', permettant de recevoir les adhésions/cotisations et frais de reconversions."|trans }}
						</em></p>
						<div class='text-center'>{{ form_row(form.save) }}</div>
					{{form_end(form)}}
		 		</div>
		 	</div>
		</div>
	</div>
{% endblock %}

templates/themes/kohinos/page.html.twig
{% set title = page.name %}
{% set description = page.metadescription %}
{% set keywords = page.metakeywords %}
{% extends '@kohinos/common/layout.html.twig' %}

{% if page.css %}
	{% block css %}
		{{parent()}}
		{{ page.css|raw }}
	{% endblock css %}
{% endif %}

{% if page.js %}
	{% block js %}
		{{parent()}}
		{{ page.js|raw }}
	{% endblock js %}
{% endif %}

{% block content %}
<div class='container'>
	<h4>{{page.title}}</h4>
	<p class="paragraf">
		{{page.content|raw}}
	</p>
</div>
{% endblock %}