src/Entity/Adherent.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Entity\EntityTrait\EnablableEntityTrait;
use App\Entity\EntityTrait\GeolocEntityTrait;
use App\Entity\EntityTrait\HasAccountsTrait;
use App\Entity\EntityTrait\HasEcompteEntity;
use App\Flux\AccountableInterface;
use App\Flux\AccountableObject;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * ApiResource(
 *     attributes={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_VIEW')"},
 *     collectionOperations={
 *         "get"={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_LIST')"},
 *         "post"={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_EDIT')"}
 *     },
 *     itemOperations={
 *         "get"={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_LIST')"},
 *         "put"={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_EDIT') or object.user == user"},
 *     },
 *     normalizationContext={"groups"={"read"}},
 *     denormalizationContext={"groups"={"write"}}
 * ).
 *
 * @ORM\Entity(repositoryClass="App\Repository\AdherentRepository")
 * @ORM\Table(name="adherent")
 * @ORM\HasLifecycleCallbacks()
 */
class Adherent extends AccountableObject implements AccountableInterface
{
    use EnablableEntityTrait;
    use TimestampableEntity;
    use GeolocEntityTrait;
    use HasEcompteEntity;
    use HasAccountsTrait;

    /**
     * @var \Ramsey\Uuid\UuidInterface
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="idmlc", type="string", length=100, nullable=true)
     * @Groups({"read", "write"})
     */
    protected $idmlc;

    /**
     * @var User
     *
     * @ORM\OneToOne(targetEntity="User", cascade={"all"}, mappedBy="adherent", fetch="LAZY")
     */
    protected $user;

    /**
     * @var Groupe
     *
     * @ORM\ManyToOne(targetEntity="Groupe", inversedBy="adherents", fetch="LAZY")
     */
    private $groupe;

    /**
     * @var ArrayCollection|AccountAdherent[]
     * @ORM\OneToMany(targetEntity="AccountAdherent", mappedBy="adherent")
     */
    private $accounts;

    public function __construct()
    {
        $this->accounts = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * Get idmlc.
     *
     * @return
     */
    public function getIdmlc(): ?string
    {
        return $this->idmlc;
    }

    /**
     * Set idmlc.
     *
     * @return $this
     */
    public function setIdmlc(string $idmlc): self
    {
        $this->idmlc = $idmlc;

        return $this;
    }

    public function getCompte(): float
    {
        return $this->getEcompte();
    }

    public function setCompte(float $ecompte): self
    {
        $this->setEcompte($ecompte);

        return $this;
    }

    /**
     * @return User
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User $user
     *
     * @return Prestataire
     */
    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @param Groupe|null $groupe
     *
     * @return $this
     */
    public function setGroupe(?Groupe $groupe): self
    {
        $this->groupe = $groupe;

        return $this;
    }

    /**
     * @return Groupe|null
     */
    public function getGroupe(): ?Groupe
    {
        return $this->groupe;
    }

    public function isEnabled(): bool
    {
        return $this->getUser()->isEnabled();
    }

    public function setEnabled($enabled): self
    {
        $this->getUser()->setEnabled($enabled);

        return $this;
    }

    public function getName(): string
    {
        return $this->__toString();
    }

    public function __toString(): string
    {
        if (!empty($this->getUser())) {
            if (!empty($this->getUser()->getLastname() . $this->getUser()->getFirstname())) {
                return $this->getUser()->getLastname() . ' ' . $this->getUser()->getFirstname();
            }
            if (!empty($this->getUser()->getUsername())) {
                return $this->getUser()->getUsername();
            }
            if (!empty($this->getUser()->getEmail())) {
                return $this->getUser()->getEmail();
            }
        }

        return 'Adhérent xxx';
    }

    public function getEmail(): ?string
    {
        if (!empty($this->getUser())) {
            return $this->getUser()->getEmail();
        }
        return '';
    }

    public function getFullname(): string
    {
        $return = '';
        if (!empty($this->getUser())) {
            if (!empty($this->getUser()->getLastname() . $this->getUser()->getFirstname())) {
                $return = $this->getUser()->getLastname() . ' ' . $this->getUser()->getFirstname();
                if (!empty($this->getUser()->getEmail())) {
                    $return .= '(' . $this->getUser()->getEmail() . ')';
                }
            } elseif (!empty($this->getUser()->getEmail())) {
                $return = $this->getUser()->getEmail();
            }

            return $return;
        }

        return 'Adhérent xxx';
    }
}

src/Entity/Siege.php
<?php

namespace App\Entity;

use App\Entity\EntityTrait\HasAccountsTrait;
use App\Entity\EntityTrait\HasCompteEntity;
use App\Entity\EntityTrait\HasEcompteEntity;
use App\Entity\EntityTrait\NameSlugContentEntityTrait;
use App\Flux\AccountableInterface;
use App\Flux\AccountableObject;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SiegeRepository")
 * @ORM\Table(name="siege")
 * @ORM\HasLifecycleCallbacks()
 */
class Siege extends AccountableObject implements AccountableInterface
{
    use NameSlugContentEntityTrait;
    use HasCompteEntity;
    use HasEcompteEntity;
    use HasAccountsTrait;

    /**
     * @var \Ramsey\Uuid\UuidInterface
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    protected $id;

    /**
     * @var ArrayCollection|Groupe[]
     * @ORM\OneToMany(targetEntity="Groupe", mappedBy="siege")
     */
    private $groupes;

    /**
     * @var float
     *
     * @ORM\Column(name="compte_nantie", type="decimal", scale=2)
     */
    private $compteNantie = 0;

    /**
     * @var float
     *
     * @ORM\Column(name="ecompte_nantie", type="decimal", scale=2)
     */
    private $ecompteNantie = 0;

    /**
     * @var ArrayCollection|AccountSiege[]
     * @ORM\OneToMany(targetEntity="AccountSiege", mappedBy="siege")
     */
    private $accounts;

    public function __construct()
    {
        $this->groupes = new ArrayCollection();
        $this->accounts = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return float
     */
    public function getCompteNantie(): float
    {
        return $this->compteNantie;
    }

    /**
     * @param float $compteNantie
     *
     * @return $this
     */
    public function setCompteNantie(float $compteNantie)
    {
        $this->compteNantie = $compteNantie;

        return $this;
    }

    /**
     * @param float $compteNantie
     *
     * @return $this
     */
    public function addCompteNantie(float $compteNantie)
    {
        $this->compteNantie += $compteNantie;

        return $this;
    }

    /**
     * @param float $compteNantie
     *
     * @return $this
     */
    public function removeCompteNantie(float $compteNantie)
    {
        $this->compteNantie -= $compteNantie;

        return $this;
    }

    /**
     * @return float
     */
    public function getEcompteNantie(): float
    {
        return $this->ecompteNantie;
    }

    /**
     * @param float $ecompteNantie
     *
     * @return $this
     */
    public function setEcompteNantie(float $ecompteNantie)
    {
        $this->ecompteNantie = $ecompteNantie;

        return $this;
    }

    /**
     * @param float $ecompteNantie
     *
     * @return $this
     */
    public function addEcompteNantie(float $ecompteNantie)
    {
        $this->ecompteNantie += $ecompteNantie;

        return $this;
    }

    /**
     * @param float $ecompteNantie
     *
     * @return $this
     */
    public function removeEcompteNantie(float $ecompteNantie)
    {
        $this->ecompteNantie -= $ecompteNantie;

        return $this;
    }

    /**
     * @return Groupe[]|ArrayCollection
     */
    public function getGroupes()
    {
        return $this->groupes;
    }

    /**
     * @param Groupe $groupe
     *
     * @return $this
     */
    public function addGroupe(Groupe $groupe)
    {
        if (!$this->groupes->contains($groupe)) {
            $this->groupes[] = $groupe;
            $groupe->setSiege($this);
        }

        return $this;
    }

    /**
     * @param Groupe $groupe
     *
     * @return $this
     */
    public function removeGroupe(Groupe $groupe)
    {
        if ($this->groupes->contains($groupe)) {
            $this->groupes->removeElement($groupe);
            $groupe->setSiege(null);
        }

        return $this;
    }

    public function __toString(): string
    {
        return 'SIEGE';
    }
}

templates/themes/kohinos/siege/block/solde_edit.html.twig
{% extends '@kohinos/block/block_collapse.html.twig' %}

{% block blocktitle %}
	<i class="fa fa-euro fa-euro-sign me-4"></i> Impression / Destruction de billets
{% endblock blocktitle %}
{% block blocksubtitle %}
{% endblock blocksubtitle %}
{% block blockcontent %}
	{% set siege = getSiege() %}
	<div class="card mb-3">
		<div class="card-body py-4"><u>{{ 'Billets au siège'|trans }}</u> : <b class='text-primary' style='font-size: 1.2rem;'>{{ siege.mlcAccount.balance }}</b></div>
	</div>
	<h5 class='text-primary'>{{ 'Impression de billets'|trans }}</h5>
	{% set form = getTicketFixPrintForm(app.user) %}
	{{ form_start(form) }}
	    {{ form_row(form.expediteur) }}
	    {{ form_row(form.destinataire) }}
	    {{ form_row(form.moyen) }}
	    {{ form_row(form.montant) }}
	    {{ form_row(form.reference) }}
	    {{ form_row(form.save) }}
	{{ form_end(form) }}
	<hr/>
	<hr/>
	<h5 class='text-primary'>{{ 'Destruction de billets'|trans }}</h5>
	{% set formDestroy = getTicketFixDestroyForm(app.user) %}
	{{ form_start(formDestroy) }}
	    {{ form_row(formDestroy.expediteur) }}
	    {{ form_row(formDestroy.destinataire) }}
	    {{ form_row(formDestroy.moyen) }}
	    {{ form_row(formDestroy.montant) }}
	    {{ form_row(formDestroy.reference) }}
	    {{ form_row(formDestroy.save) }}
	{{ form_end(formDestroy) }}

{% endblock blockcontent %}

templates/themes/kohinos/siege/block/solde_edit_page.html.twig
{% extends '@kohinos/common/layout.html.twig' %}

{% block content %}
<div class='container groupeshow mt-5 mb-5' style='max-width:800px;'>
	<h4>{{ title }} :</h4>
    {{ form_start(form) }}
	    {% if form.compte is defined %}
	    	{{ form_row(form.compte) }}
		{% endif %}
	    {% if form.save is defined %}
	    	{{ form_row(form.save) }}
	    {% endif %}
	{{ form_end(form) }}
</div>
{% endblock %}

templates/themes/kohinos/siege/block/transfert_groupesiege.html.twig
{% extends '@kohinos/block/onetransaction.html.twig' %}

{% block blocktitle %}
	<i class="fa fa-exchange fa-exchange-alt me-4"></i> {{ 'Transfert du groupe au siège'|trans }}
{% endblock blocktitle %}
{% block blockcontent %}
	{% set form = getTransfertGroupeSiegeForm(app.user) %}
	{{ parent() }}
{% endblock blockcontent %}

templates/themes/kohinos/siege/block/transfert_siegegroupe.html.twig
{% extends '@kohinos/block/onetransaction.html.twig' %}

{% block blocktitle %}
	<i class="fa fa-exchange fa-exchange-alt me-4"></i> {{ 'Transfert à un groupe'|trans }}
{% endblock blocktitle %}
{% block blockcontent %}
	{% set form = getTransfertSiegeGroupeForm(app.user) %}
	{{ parent() }}
{% endblock blockcontent %}