src/Entity/Adherent.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Entity\EntityTrait\EnablableEntityTrait;
use App\Entity\EntityTrait\GeolocEntityTrait;
use App\Entity\EntityTrait\HasAccountsTrait;
use App\Entity\EntityTrait\HasEcompteEntity;
use App\Flux\AccountableInterface;
use App\Flux\AccountableObject;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * ApiResource(
 *     attributes={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_VIEW')"},
 *     collectionOperations={
 *         "get"={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_LIST')"},
 *         "post"={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_EDIT')"}
 *     },
 *     itemOperations={
 *         "get"={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_LIST')"},
 *         "put"={"security"="is_granted('ROLE_ADMIN_ADHERENT_GERER_EDIT') or object.user == user"},
 *     },
 *     normalizationContext={"groups"={"read"}},
 *     denormalizationContext={"groups"={"write"}}
 * ).
 *
 * @ORM\Entity(repositoryClass="App\Repository\AdherentRepository")
 * @ORM\Table(name="adherent")
 * @ORM\HasLifecycleCallbacks()
 */
class Adherent extends AccountableObject implements AccountableInterface
{
    use EnablableEntityTrait;
    use TimestampableEntity;
    use GeolocEntityTrait;
    use HasEcompteEntity;
    use HasAccountsTrait;

    /**
     * @var \Ramsey\Uuid\UuidInterface
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="idmlc", type="string", length=100, nullable=true)
     * @Groups({"read", "write"})
     */
    protected $idmlc;

    /**
     * @var User
     *
     * @ORM\OneToOne(targetEntity="User", cascade={"all"}, mappedBy="adherent", fetch="LAZY")
     */
    protected $user;

    /**
     * @var Groupe
     *
     * @ORM\ManyToOne(targetEntity="Groupe", inversedBy="adherents", fetch="LAZY")
     */
    private $groupe;

    /**
     * @var ArrayCollection|AccountAdherent[]
     * @ORM\OneToMany(targetEntity="AccountAdherent", mappedBy="adherent")
     */
    private $accounts;

    public function __construct()
    {
        $this->accounts = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * Get idmlc.
     *
     * @return
     */
    public function getIdmlc(): ?string
    {
        return $this->idmlc;
    }

    /**
     * Set idmlc.
     *
     * @return $this
     */
    public function setIdmlc(string $idmlc): self
    {
        $this->idmlc = $idmlc;

        return $this;
    }

    public function getCompte(): float
    {
        return $this->getEcompte();
    }

    public function setCompte(float $ecompte): self
    {
        $this->setEcompte($ecompte);

        return $this;
    }

    /**
     * @return User
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User $user
     *
     * @return Prestataire
     */
    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @param Groupe|null $groupe
     *
     * @return $this
     */
    public function setGroupe(?Groupe $groupe): self
    {
        $this->groupe = $groupe;

        return $this;
    }

    /**
     * @return Groupe|null
     */
    public function getGroupe(): ?Groupe
    {
        return $this->groupe;
    }

    public function isEnabled(): bool
    {
        return $this->getUser()->isEnabled();
    }

    public function setEnabled($enabled): self
    {
        $this->getUser()->setEnabled($enabled);

        return $this;
    }

    public function getName(): string
    {
        return $this->__toString();
    }

    public function __toString(): string
    {
        if (!empty($this->getUser())) {
            if (!empty($this->getUser()->getLastname() . $this->getUser()->getFirstname())) {
                return $this->getUser()->getLastname() . ' ' . $this->getUser()->getFirstname();
            }
            if (!empty($this->getUser()->getUsername())) {
                return $this->getUser()->getUsername();
            }
            if (!empty($this->getUser()->getEmail())) {
                return $this->getUser()->getEmail();
            }
        }

        return 'Adhérent xxx';
    }

    public function getEmail(): ?string
    {
        if (!empty($this->getUser())) {
            return $this->getUser()->getEmail();
        }
        return '';
    }

    public function getFullname(): string
    {
        $return = '';
        if (!empty($this->getUser())) {
            if (!empty($this->getUser()->getLastname() . $this->getUser()->getFirstname())) {
                $return = $this->getUser()->getLastname() . ' ' . $this->getUser()->getFirstname();
                if (!empty($this->getUser()->getEmail())) {
                    $return .= '(' . $this->getUser()->getEmail() . ')';
                }
            } elseif (!empty($this->getUser()->getEmail())) {
                $return = $this->getUser()->getEmail();
            }

            return $return;
        }

        return 'Adhérent xxx';
    }
}

src/Entity/Don.php
<?php

namespace App\Entity;

use App\Enum\CurrencyEnum;
use App\Enum\MoyenEnum;
use App\Utils\OperationFactory;
use Doctrine\ORM\Mapping as ORM;

/**
 * Don d'un utilisateur.
 *
 * @ORM\Entity
 */
class Don extends Flux
{
    const TYPE_DON_ADHERENT = 'don_adherent';
    const TYPE_DON_PRESTATAIRE = 'don_prestataire';

    /**
     * @ORM\OneToOne(targetEntity="Prestataire")
     * @ORM\JoinColumn(name="prestataire_dest_id", referencedColumnName="id", nullable=true)
     */
    protected $destinataire;

    /**
     * Constructeur.
     */
    public function __construct()
    {
        parent::__construct();
    }

    public static function getAvailableTypes(): array
    {
        return [
            self::TYPE_DON_ADHERENT => self::TYPE_DON_ADHERENT,
            self::TYPE_DON_PRESTATAIRE => self::TYPE_DON_PRESTATAIRE,
        ];
    }

    public function getAllOperations($em)
    {
        if (MoyenEnum::MOYEN_EMLC == $this->getMoyen()) {
            return [
                OperationFactory::getOperation($this, $this->getExpediteur(), CurrencyEnum::CURRENCY_EMLC, -$this->getMontant()),
                OperationFactory::getOperation($this, $this->getDestinataire(), CurrencyEnum::CURRENCY_EMLC, $this->getMontant()),
            ];
        } elseif (MoyenEnum::MOYEN_CB == $this->getMoyen()) {
            return [
                OperationFactory::getOperation($this, $this->getDestinataire(), CurrencyEnum::CURRENCY_EURO, $this->getMontant()),
            ];
        }

        return [];
    }

    public function operate($em)
    {
        if (MoyenEnum::MOYEN_MLC == $this->getMoyen()) {
            $compteExp = $this->getExpediteur()->getEcompte() - $this->getMontant();
            if ($compteExp < 0) {
                throw new \Exception('[FLUX] Opération impossible ! Montant supérieur au solde de monnaie éléctronique !');
            } else {
                $this->getExpediteur()->removeEcompte($this->getMontant());
                $this->getDestinataire()->addEcompte($this->getMontant());

                return [$this->getExpediteur(), $this->getDestinataire()];
            }
        }
        // Pas d'opération si la cotisation se fait par CB
        return [];
    }

    public function getUsersToNotify()
    {
        return [];
    }

    /**
     * @return string
     */
    public function getParenttype(): string
    {
        return parent::TYPE_DON;
    }

    /**
     * @return string
     */
    public function getType(): string
    {
        return '';
    }

    public function __toString(): string
    {
        if (empty($this->getDestinataire()) || empty($this->getExpediteur()) || null === $this->getMontant()) {
            return '[FLUX] Visualisation impossible ! Destinataire / Expéditeur et/ou montant manquant(s) !';
        }

        return ucwords(str_replace('_', ' ', $this->getType())) . ' : ' . $this->getExpediteur() . ' : ' . $this->getMontant() . '€' . ($this->getCreatedAt() ? ' (le ' . $this->getCreatedAt()->format('d/m/Y H:i') . ')' : '');
    }
}

templates/themes/kohinos/adherent/adherer.html.twig
{% extends '@kohinos/common/layout.html.twig' %}

{% block content %}
<div class='container' style='max-width:800px;'>
	<div class='text-center mb-5 mt-2'>
		<h4 class='mt-3'><b>{{'Adhérer'|trans }}</b></h4>
	</div>
	{% if KOH_USE_PAYZEN == 'true' or KOH_USE_HELLOASSO == 'true' %}
		<p>
		{% if KOH_ADHESION_TEXT|default('') != '' %}
			{{ KOH_ADHESION_TEXT }}
		{% endif %}
		</p>
		{{form_start(form)}}
			{{ form_row(form.user) }}
			{% if form.groupe is defined %}
				{{ form_row(form.groupe) }}
			{% endif %}
			{{ form_row(form.geoloc) }}
			{{ form_row(form.cotisation) }}
			<div class='text-center mb-5 mt-2'>
				{% if form.save is defined %}
					{{ form_widget(form.save) }}
				{% endif %}
				{% if form.saveHelloAsso is defined %}
					{{ form_widget(form.saveHelloAsso) }}
				{% endif %}
			</div>
		{{form_end(form)}}
	{% else %}
		<div class='text-center mb-5 mt-2'>
			<p><i>Vous ne pouvez malheureusement pas adhérer ici, le paiement n'est pas configuré sur cette application.</i></p>
		</div>
	{% endif %}
</div>
{% endblock %}

templates/themes/kohinos/adherent/infos.html.twig
{% extends '@kohinos/common/layout.html.twig' %}

{% block content %}
<div class='container adherent_infos'>
	<div class="row">
		<div class="col-6">
			<div class='infos mt-4'>
				<h4>{{ "Modifier mes informations"|trans }} :</h4>
				<p>
					{{ form_start(form) }}
						{{ form_row(form.user) }}
						{{ form_row(form.geoloc) }}
						{{ form_row(form.groupe) }}
						{{ form_row(form.save) }}
					{{ form_end(form) }}
				</p>
			</div>
		</div>
		<div class="col-6">
			{% if app.user.adherent is not null and app.user.adherent.emlcAccount.balance >= 0 %}
				<div class='ecompte mt-4'>
					<h4>{{ "Mon ecompte"|trans }} :</h4>
					<ul class='list-group'>
						<li class="list-group-item">{{(app.user.adherent.emlcAccount.balance)|number_format(2, '.', ',')}}</li>
					</ul>
				</div>
			{% endif %}
			{# @TODO : afficher les cotisations #}
			{# {% if app.user.adherent.cotisations|length > 0 %}
				<div class='cotisations mt-4'>
					<h4>{{ "Mes cotisations"|trans }} :</h4>
					<ul class='list-group'>
						{% for cotisation in app.user.adherent.cotisations %}
							<li class="list-group-item">{{cotisation.annee|upper}} : {{cotisation.montant}}&euro; ({{ 'payée le'|trans }} {{cotisation.createdAt|date('d-m-Y')}})</li>
						{% endfor %}
					</ul>
				</div>
			{% endif %} #}
			{# {% if app.user.flux|length > 0 %}
				<div class='flux mt-4'>
					<h4>{{ "Mes transactions"|trans }} :</h4>
					<ul class='list-group'>
						{% for flux in app.user.flux %}
							<li class="list-group-item">{{flux.parenttype|capitalize}} à {{flux.destinataire}} {{flux.montant}}&euro; ({{ 'payée le'|trans }} {{flux.createdAt|date('d-m-Y')}})</li>
						{% endfor %}
					</ul>
				</div>
			{% endif %} #}
		</div>
	</div>
</div>
{% endblock %}